version: '3'
services:

  local-aws-lambda:
    build: .
    ports:
      - '8081:8080'
    environment:
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=http://minio:9000
      - AWS_USE_PATH_STYLE_ENDPOINT=true
      - DEST_BUCKET_NAME=gh-archive-data-raw
    networks:
      - oss_gharchivedata_orchestration_airflow_default

networks:
  oss_gharchivedata_orchestration_airflow_default:
    external: true



