version: '3'
services:

  local-aws-lambda:
    build: .
    ports:
      - '8081:8080'
    environment:
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=http://minio:9000
      - AWS_USE_PATH_STYLE_ENDPOINT=true
      - DEST_BUCKET_NAME=gh-archive-data-raw
    networks:
      - oss_gharchivedata_orchestration_airflow_default
      
  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"
    networks:
      - oss_gharchivedata_orchestration_airflow_default

  minio-init-buckets:
    image: minio/mc:latest
    tty: true 
    depends_on:
      - minio
    entrypoint: > 
        /bin/sh -c "
        /usr/bin/mc alias set local http://minio:9000 root password;
        /usr/bin/mc mb --ignore-existing local/gh-archive-data-raw;
        /usr/bin/mc mb --ignore-existing local/gh-archive-data-curated;
        /usr/bin/mc mb --ignore-existing local/gh-archive-data-analytics;
        " 
    networks:
      - oss_gharchivedata_orchestration_airflow_default

volumes:
  minio:
    driver: local

networks:
  oss_gharchivedata_orchestration_airflow_default:
    external: true



